// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIeoJXiPutWEt5vAXwNGVhK74_65VHBec',
    appId: '1:348522602110:web:34d37b6a7b98e4b7d7022f',
    messagingSenderId: '348522602110',
    projectId: 'movies-app-73ad2',
    authDomain: 'movies-app-73ad2.firebaseapp.com',
    storageBucket: 'movies-app-73ad2.firebasestorage.app',
    measurementId: 'G-K4QME5L00G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCmWGoGAiU9ZxoR0TP2guGyyPBITpFs_xE',
    appId: '1:348522602110:android:edf74e54870d194dd7022f',
    messagingSenderId: '348522602110',
    projectId: 'movies-app-73ad2',
    storageBucket: 'movies-app-73ad2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPUZWtdpuYCNvHdfpvXNqLaytYmSnNQ20',
    appId: '1:348522602110:ios:ff7471de34d70c0fd7022f',
    messagingSenderId: '348522602110',
    projectId: 'movies-app-73ad2',
    storageBucket: 'movies-app-73ad2.firebasestorage.app',
    iosBundleId: 'com.example.moviesAppProject',
  );
}
